//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atomia.Custom.IntermediateSts.Configuration
{
    
    
    /// <summary>
    /// The StsConfigurationSection Configuration Section.
    /// </summary>
    public partial class StsConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the StsConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string StsConfigurationSectionSectionName = "stsConfigurationSection";
        
        /// <summary>
        /// The XML path of the StsConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string StsConfigurationSectionSectionPath = "stsConfigurationSection";
        
        /// <summary>
        /// Gets the StsConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public static global::Atomia.Custom.IntermediateSts.Configuration.StsConfigurationSection Instance
        {
            get
            {
                return ((global::Atomia.Custom.IntermediateSts.Configuration.StsConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::Atomia.Custom.IntermediateSts.Configuration.StsConfigurationSection.StsConfigurationSectionSectionPath)));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region RelayingParties Property
        /// <summary>
        /// The XML name of the <see cref="RelayingParties"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string RelayingPartiesPropertyName = "relayingParties";
        
        /// <summary>
        /// Gets or sets the RelayingParties.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The RelayingParties.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Atomia.Custom.IntermediateSts.Configuration.StsConfigurationSection.RelayingPartiesPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Atomia.Custom.IntermediateSts.Configuration.RelayingParties RelayingParties
        {
            get
            {
                return ((global::Atomia.Custom.IntermediateSts.Configuration.RelayingParties)(base[global::Atomia.Custom.IntermediateSts.Configuration.StsConfigurationSection.RelayingPartiesPropertyName]));
            }
            set
            {
                base[global::Atomia.Custom.IntermediateSts.Configuration.StsConfigurationSection.RelayingPartiesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Atomia.Custom.IntermediateSts.Configuration
{
    
    
    /// <summary>
    /// A collection of RelayingParty instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Atomia.Custom.IntermediateSts.Configuration.RelayingParties.RelayingPartyPropertyName)]
    public partial class RelayingParties : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string RelayingPartyPropertyName = "relayingParty";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::Atomia.Custom.IntermediateSts.Configuration.RelayingParties.RelayingPartyPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Atomia.Custom.IntermediateSts.Configuration.RelayingParties.RelayingPartyPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty)(element)).name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty this[int index]
        {
            get
            {
                return ((global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty this[object name]
        {
            get
            {
                return ((global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="relayingParty">The <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty relayingParty)
        {
            base.BaseAdd(relayingParty);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="relayingParty">The <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty relayingParty)
        {
            base.BaseRemove(this.GetElementKey(relayingParty));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty GetItemAt(int index)
        {
            return ((global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty GetItemByKey(string name)
        {
            return ((global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Atomia.Custom.IntermediateSts.Configuration
{
    
    
    /// <summary>
    /// The RelayingParty Configuration Element.
    /// </summary>
    public partial class RelayingParty : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region name Property
        /// <summary>
        /// The XML name of the <see cref="name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string namePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.namePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string name
        {
            get
            {
                return ((string)(base[global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.namePropertyName]));
            }
            set
            {
                base[global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.namePropertyName] = value;
            }
        }
        #endregion
        
        #region certificate Property
        /// <summary>
        /// The XML name of the <see cref="certificate"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string certificatePropertyName = "certificate";
        
        /// <summary>
        /// Gets or sets the certificate.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The certificate.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.certificatePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string certificate
        {
            get
            {
                return ((string)(base[global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.certificatePropertyName]));
            }
            set
            {
                base[global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.certificatePropertyName] = value;
            }
        }
        #endregion
        
        #region homeRealm Property
        /// <summary>
        /// The XML name of the <see cref="homeRealm"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string homeRealmPropertyName = "homeRealm";
        
        /// <summary>
        /// Gets or sets the homeRealm.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The homeRealm.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.homeRealmPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string homeRealm
        {
            get
            {
                return ((string)(base[global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.homeRealmPropertyName]));
            }
            set
            {
                base[global::Atomia.Custom.IntermediateSts.Configuration.RelayingParty.homeRealmPropertyName] = value;
            }
        }
        #endregion
    }
}
